package pushdown;

import pushdown.reader.PDAReader;
import tape.Tape;
import tape.reader.TapeReader;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

/**
 * <h2>Main</h2>
 *
 * @author Cristian Abrante
 * @version 1.0.0
 */
public class Main {
  public static void main(String[] args) throws FileNotFoundException {
    if (args.length <= 0 || args.length > 3)
      System.err.println("Incorrect number of arguments.");

    boolean log = args[0].equals("log");
    String ApFileName = log ? args[1] : args[0];
    String tapeFileName = null;

    if (args.length == 3)
      tapeFileName = args[2];
    if (args.length == 2 && !log)
      tapeFileName = args[1];

    PDAReader pdaReader = new PDAReader(new FileReader(ApFileName));
    PushdownAutomaton pda = pdaReader.getReadedPDA();
    TapeReader tapeReader = null;
    System.out.println(pda);

    if (tapeFileName == null) {
      Scanner scanner = new Scanner(System.in);
      System.out.println("Enter the tape input > ");
      String tapeDefinition = scanner.nextLine();

      tapeReader = new TapeReader(tapeDefinition);
    } else {
      tapeReader = new TapeReader(new FileReader(tapeFileName));
    }

    Tape tape = new Tape(tapeReader.getTokenizedInput(), pda.getInputAlphabet());

    pda.isPrintable = log;
    boolean belongs = pda.evaluate(tape);

    tape.setCurrentPosition(0);

    System.out.println();
    System.out.println("String " + tape + " "
            + (belongs? "belongs" : "not belongs")
            + " to the language generated by the automaton.");

    System.out.println();
    System.out.println("Done by: Cristian Abrante");
  }
}
